Feature#18-MarkMap
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team1 pull request #35
Opened 2023-03-13 23:46 UTC by Leonardo-Aguirre-Ponce

Added the function of marking locations on the map to place the location of disaster sites

### What?
-  Marker on the map added in the add record screen.
- See Initializing the React Native project #34 for more information.

### Why
- In order to add the location of the damage in add record screen.
- See Initializing the React Native project #34 for more information.

## Testing
- Since the project is just initialized you only need install the basic packages to visualize the application
```npm install```
- then you can initialize with an android emulator or via web
```npm start```

## Screenshots
| Proposed design   |      Successful design      |
|:----------:|:-------------:|
| ![image](https://user-images.githubusercontent.com/72171210/224856180-f330083c-e09d-4382-9474-bb6f935cdefd.png) | ![image](https://user-images.githubusercontent.com/72171210/224856366-bb5d23a1-2dd0-42ca-af79-8950ab37a66b.png) |

2023-03-13 23:53 UTC, beatrizheav approved these changes

2023-03-14 00:08 UTC, McFly1208 approved these changes
LGTM

2023-03-14 00:09 UTC, QuackDuster approved these changes

2023-03-14 00:32 UTC, yovanha approved these changes

2023-03-14 00:44 UTC, YilKanda requested changes

2023-03-14 00:44 UTC, YilKanda commented on src/views/AddRecord.jsx
> +    console.log("makern", this.state.markerLocation);
Don't leave test code on GitHub, like console.log()

2023-03-14 22:19 UTC, Leonardo-Aguirre-Ponce commented on src/views/AddRecord.jsx
> +    console.log("makern", this.state.markerLocation);
Done

2023-03-14 22:35 UTC, merged