Feature#23 textinput validation
BrightCoders-Institute/BCDIC22-RN-proyecto-final-team1 pull request #47
Opened 2023-03-25 01:21 UTC by gadd0609

# Description

### What?
-  Implemented the validation whit formik in the login and signup screen.
- See Initializing the React Native project #44  for more information
### Why
- In order to ensure that the data entered in the form is valid and consistent before it is sent to the server or stored in the database.
- See Initializing the React Native project #44  for more information.
## Testing
- Since the project is just initialized you only need install the basic packages to visualize the application
```npm install```
- then you can initialize with an android emulator or via web
```npm start```
## Screenshots
|      Successful design      |
|:-------------:|
 |  ![image](https://user-images.githubusercontent.com/50815656/227674873-4cbe7d70-6734-4739-8e99-03fd718882cd.png)![image](https://user-images.githubusercontent.com/50815656/227674778-5c73323e-7da0-4d26-a55b-9ee68dc8aa1e.png) |

2023-03-25 01:23 UTC, EliasCode79 approved these changes
LGTM

2023-03-25 01:38 UTC, IvanGodinez21 approved these changes

2023-03-25 01:44 UTC, yovanha requested changes

2023-03-25 01:44 UTC, yovanha commented on src/views/SignUpScreen.jsx
> +            }}
It's not recommendable to fill your components with logic code, could you please move this to a function and add that function to this `validate` prop? You could put that function after line 79.

2023-03-25 13:45 UTC, garzo94 approved these changes

2023-03-28 23:44 UTC, yovanha approved these changes
Good work!👍🏻

2023-03-29 00:17 UTC, merged